Fixed warning when tapping homebrew/core /opt/homebrew/bin is not in your PATH
fs/osx-bootstrap pull request #133
Opened 2021-07-06 13:01 UTC by DenisZackharov

I add copy if .bashrc and .zshrc not founded and edit .bashrc and .zshrc to fix the installation Homebrew casks.

2021-07-06 13:02 UTC, DenisZackharov commented on modules/brew.bash
> -osx_bootstrap="$(cd "$(dirname "$0")/.." && pwd -P)"
zsh is not supported this now

2021-07-06 14:21 UTC, DmitryBarskov requested changes

2021-07-06 14:21 UTC, DmitryBarskov commented on modules/brew.bash
> +osx_bootstrap="$(cd "$(dirname "$self")/.." && pwd -P)"
You should use `$0` for getting current script name

2021-07-06 14:21 UTC, DmitryBarskov commented on modules/brew.bash
> +if [ -f ~/.bashrc ] && [ -f ~/.zshrc ]
It is `.bash_profile` for mac os

2021-07-06 14:21 UTC, DmitryBarskov commented on modules/brew.bash
> +else
What if I have only `.bash_profile` and it's ok for me?

2021-07-06 14:21 UTC, DmitryBarskov commented on modules/brew.bash
> +  echo 'export PATH=/opt/homebrew/bin:$PATH' >> ~/.bashrc
Use `$HOME` variable instead of tilde in scripts.

2021-07-06 14:21 UTC, DmitryBarskov commented on modules/brew.bash
> +  echo 'export PATH=/opt/homebrew/bin:$PATH' >> ~/.bashrc
Why do you add this to configuration file? Can't you just export this?
```suggestion
export PATH=/opt/homebrew/bin:$PATH
```

2021-07-06 14:21 UTC, DmitryBarskov commented on modules/brew.bash
> +brew bundle install --file="$osx_bootstrap/Brewfile"
remove trailing whitespace

2021-07-06 14:21 UTC, DmitryBarskov commented on modules/brew.bash
> +osx_bootstrap="$(cd "$(dirname "$self")/.." && pwd -P)"
remove trailing whitespace

2021-07-06 14:21 UTC, DmitryBarskov commented on modules/node.bash
> +#For remove semaphoreci warning
It's clear enough even without this comment.
```suggestion

```

2021-07-08 08:33 UTC, DmitryBarskov commented on modules/brew.bash
> +  export PATH="/opt/homebrew/bin:$PATH"
```suggestion
export PATH="/opt/homebrew/bin:$PATH"
```

2021-07-12 11:00 UTC, merged